### ISSUE TITLE
Submissions Stuck Again for Competition 4430

### ISSUE THREAD

**Issue by archettialberto** [codalab/codabench#1666]
Dear Codabench Team,

We are running the competition https://www.codabench.org/competitions/4430. The issue of stuck submissions on Internal Server Error 500 is back. From 4PM today all workers on our servers return errors like the following. 
How should we handle this issue?

On a side note, following #1664, these are the last days of competition and the website is becoming extremely slow when trying to load submissions. Is there a way to solve this? 

```
an2dl-worker7  | [2024-11-16 22:06:12,120: INFO/ForkPoolWorker-1] Updating submission @ https://www.codabench.org/api/submissions/159973/ with data = {'status': 'Preparing', 'status_details': None, 'secret': '...'}
an2dl-worker7  | [2024-11-16 22:06:13,775: INFO/ForkPoolWorker-1] Submission patch failed with status = 500, and response =
an2dl-worker7  | b'<h1>Server Error (500)</h1>'
an2dl-worker7  | [2024-11-16 22:06:13,775: INFO/ForkPoolWorker-1] Updating submission @ https://www.codabench.org/api/submissions/159973/ with data = {'status': 'Failed', 'status_details': 'Failure updating submission data.', 'secret': '...'}
an2dl-worker7  | [2024-11-16 22:06:13,838: INFO/ForkPoolWorker-1] Submission patch failed with status = 500, and response =
an2dl-worker7  | b'<h1>Server Error (500)</h1>'
an2dl-worker7  | [2024-11-16 22:06:13,838: INFO/ForkPoolWorker-1] Destroying submission temp dir: /codabench/tmpkn55zvfz
an2dl-worker7  | [2024-11-16 22:06:13,840: ERROR/ForkPoolWorker-1] Task compute_worker_run[fe0f09c7-6a74-46b8-bc27-cb29a3f74890] raised unexpected: SubmissionException('Failure updating submission data.')
an2dl-worker7  | Traceback (most recent call last):
an2dl-worker7  |   File "/compute_worker.py", line 112, in run_wrapper
an2dl-worker7  |     run.prepare()
an2dl-worker7  |   File "/compute_worker.py", line 765, in prepare
an2dl-worker7  |     self._update_status(STATUS_PREPARING)
an2dl-worker7  |   File "/compute_worker.py", line 356, in _update_status
an2dl-worker7  |     self._update_submission(data)
an2dl-worker7  |   File "/compute_worker.py", line 339, in _update_submission
an2dl-worker7  |     raise SubmissionException("Failure updating submission data.")
an2dl-worker7  | compute_worker.SubmissionException: Failure updating submission data.
an2dl-worker7  |
an2dl-worker7  | During handling of the above exception, another exception occurred:
an2dl-worker7  |
an2dl-worker7  | Traceback (most recent call last):
an2dl-worker7  |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 385, in trace_task
an2dl-worker7  |     R = retval = fun(*args, **kwargs)
an2dl-worker7  |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 650, in __protected_call__
an2dl-worker7  |     return self.run(*args, **kwargs)
an2dl-worker7  |   File "/compute_worker.py", line 120, in run_wrapper
an2dl-worker7  |     run._update_status(STATUS_FAILED, str(e))
an2dl-worker7  |   File "/compute_worker.py", line 356, in _update_status
an2dl-worker7  |     self._update_submission(data)
an2dl-worker7  |   File "/compute_worker.py", line 339, in _update_submission
an2dl-worker7  |     raise SubmissionException("Failure updating submission data.")
an2dl-worker7  | compute_worker.SubmissionException: Failure updating submission data.
```

**Comment by ObadaS** [comment]
Hello, I fixed the issue for now. You can check https://github.com/codalab/codabench/issues/1446 to know more about this particular problem and to know when we have a more permanent fix.

As for the overall platform performance, we are also working on various optimizations to make it more responsive

**Comment by archettialberto** [comment]
Thank you for the help!

We are expecting a lot of submissions between the 20th and 22nd November, since we will move to a different phase of our competition. Would deleting submissions from the previous phase improve the overall performance? At least this way we could stop/rerun some submissions manually, as right now the submission list takes minutes to load.

**Comment by archettialberto** [comment]
Hi @ObadaS,

It seems that today we have another connectivity issue with the platform. Any page of our competition (4430) takes minutes to load and most of our workers show logs similar to the following. Also, submissions from around 8PM (Europe/Rome time) all submissions are stuck in the "Preparing" phase. 
```
an2dl-worker0  | [2024-11-17 20:20:58,189: ERROR/ForkPoolWorker-3] Task compute_worker_run[0a204840-d368-46be-ac22-74f42f6d4c89] raised unexpected: ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='www.codabench.org', port=443): Read timed out. (read timeout=150)"))
an2dl-worker0  | Traceback (most recent call last):
an2dl-worker0  |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 384, in _make_request
an2dl-worker0  |     six.raise_from(e, None)
an2dl-worker0  |   File "<string>", line 2, in raise_from
an2dl-worker0  |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 380, in _make_request
an2dl-worker0  |     httplib_response = conn.getresponse()
an2dl-worker0  |   File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
an2dl-worker0  |     response.begin()
an2dl-worker0  |   File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
an2dl-worker0  |     version, status, reason = self._read_status()
an2dl-worker0  |   File "/usr/local/lib/python3.9/http/client.py", line 281, in _read_status
an2dl-worker0  |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
an2dl-worker0  |   File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
an2dl-worker0  |     return self._sock.recv_into(b)
an2dl-worker0  |   File "/usr/local/lib/python3.9/ssl.py", line 1275, in recv_into
an2dl-worker0  |     return self.read(nbytes, buffer)
an2dl-worker0  |   File "/usr/local/lib/python3.9/ssl.py", line 1133, in read
an2dl-worker0  |     return self._sslobj.read(len, buffer)
an2dl-worker0  | socket.timeout: The read operation timed out
an2dl-worker0  |
an2dl-worker0  | During handling of the above exception, another exception occurred:
an2dl-worker0  |
an2dl-worker0  | Traceback (most recent call last):
an2dl-worker0  |   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
an2dl-worker0  |     resp = conn.urlopen(
an2dl-worker0  |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 637, in urlopen
an2dl-worker0  |     retries = retries.increment(method, url, error=e, _pool=self,
an2dl-worker0  |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 368, in increment
an2dl-worker0  |     raise six.reraise(type(error), error, _stacktrace)
an2dl-worker0  |   File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 686, in reraise
an2dl-worker0  |     raise value
an2dl-worker0  |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 597, in urlopen
an2dl-worker0  |     httplib_response = self._make_request(conn, method, url,
an2dl-worker0  |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
an2dl-worker0  |     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
an2dl-worker0  |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
an2dl-worker0  |     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
an2dl-worker0  | urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.codabench.org', port=443): Read timed out. (read timeout=150)
an2dl-worker0  |
an2dl-worker0  | During handling of the above exception, another exception occurred:
an2dl-worker0  |
an2dl-worker0  | Traceback (most recent call last):
an2dl-worker0  |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 385, in trace_task
an2dl-worker0  |     R = retval = fun(*args, **kwargs)
an2dl-worker0  |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 650, in __protected_call__
an2dl-worker0  |     return self.run(*args, **kwargs)
an2dl-worker0  |   File "/compute_worker.py", line 112, in run_wrapper
an2dl-worker0  |     run.prepare()
an2dl-worker0  |   File "/compute_worker.py", line 765, in prepare
an2dl-worker0  |     self._update_status(STATUS_PREPARING)
an2dl-worker0  |   File "/compute_worker.py", line 356, in _update_status
an2dl-worker0  |     self._update_submission(data)
an2dl-worker0  |   File "/compute_worker.py", line 334, in _update_submission
an2dl-worker0  |     resp = self.requests_session.patch(url, data, timeout=150)
an2dl-worker0  |   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 596, in patch
an2dl-worker0  |     return self.request('PATCH', url, data=data, **kwargs)
an2dl-worker0  |   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 524, in request
an2dl-worker0  |     resp = self.send(prep, **send_kwargs)
an2dl-worker0  |   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 637, in send
an2dl-worker0  |     r = adapter.send(request, **kwargs)
an2dl-worker0  |   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
an2dl-worker0  |     raise ReadTimeout(e, request=request)
an2dl-worker0  | requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.codabench.org', port=443): Read timed out. (read timeout=150)
```
Could we take any action to improve the system?

Thanks for all the support!

**Comment by ObadaS** [comment]
Hello, I fixed it for now.

Deleting all the submissions that were stuck might help improve the overall loading. As of now, every submission is loaded when the competition page is loaded, which is what slows down the website.

**Comment by archettialberto** [comment]
Hi, thanks for the prompt response!

Unfortunately, the workers still show the `Read timed out` error. From our side, intervening manually on all current pending submissions is extremely difficult, as any operation on the submissions list takes minutes from the competition page. Do you have any suggestion in how to handle this? Our goal is to get back (and ensure) an operational state for as much time as possible.

**Comment by ObadaS** [comment]
We will discuss with the team about making quick changes in the code to potentially make it either easier to mass delete or to improve the loading performance. I will get back to you with more information soon hopefully

**Comment by ObadaS** [comment]
Thank you for the feedback, I will make sure to bring it to the team's attention

**Comment by ObadaS** [comment]
Hello, 
We pushed a patch yesterday to fix the slow loading issues of the website.

**Comment by archettialberto** [comment]
Hi! Yes, from yesterday night the website loading speed improved a lot. Also, deleting all submissions from the Development phase helped much. Thanks for the support!

**Comment by ObadaS** [comment]
@archettialberto I fixed it, should be fine for now

**Comment by archettialberto** [comment]
Thanks for the prompt support! Submissions are currently running 💪

I'll reopen the issue in case this problem shows again.
