### ISSUE TITLE
Submission Issue

### ISSUE THREAD

**Issue by deepsana** [codalab/codabench#1698]
***This is a template, please remove any non-relevant details to your issue***

If you are competition participant:

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

- [Competition](https://www.codabench.org/competitions/4588/)

The submission by participants gets stuck on `Submitted`. Their competition is almost over (one more development phase day and and test phase day left). Is there a way to help fix it? 
username:deepsana

**Comment by ObadaS** [comment]
Hello, there was a problem on our end which is now fixed

**Comment by deepsana** [comment]
The issue is back again @ObadaS and it's stuck on `Submitted` for the competition (https://www.codabench.org/competitions/4588/). Is it possible to fix? Thank you.

**Comment by ObadaS** [comment]
Hello @deepsana, thank you for the report. I have fixed the issue again.
Hopefully, the issue will be permanently fixed when we release the next update of Codabench
You can keep an eye on https://github.com/codalab/codabench/pull/1694 to keep track of the upcoming update.

**Comment by deepsana** [comment]
Thank you so much!!!! @ObadaS
